# Generated by Django 5.2.6 on 2025-12-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[("P", "Present"), ("A", "Absent"), ("C", "Cancelled")],
                max_length=1,
            ),
        ),
    ]
